version: '3.8'

services: 
    mysqldb:
        image: mysql
        restart: always
        env_file: ./.env
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
        ports:
            - $MYSQL_PORT:$MYSQL_DOCKER_PORT
        volumes: 
            - ./__container_caches/db/data/:/var/lib/mysql
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: node-mysql-app
        env_file: ./.env
        ports:
            - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
            - 9229:9229
        depends_on:
            - mysqldb
        stdin_open: true
        tty: true
        volumes:
            - ./logs:/app/logs
            - ./src:/app/src